### PR TITLE
Added firbolg race

### PR DESCRIPTION
**Pull request by cokelito1**
added firbolg race

btw it seems there is a problem with my config and line endings because i didn't edit ~2000 lines are you using linux no? i don't know how to resolve this problem

### CODE REVIEW

**Comment by mattearly** [comment]
hmm got a seg fault when building with the new race after picking langs, haven't looked into in detail yet. Going to work on this some today. Going to add feral teifling and see about making the race adding a little more modular so it will be easier to work with in the future

**Comment by mattearly** [comment]
Firbolg is merged into build6dev branch, wooo that was tricky. Github now thinks you wrote the entire character.cpp file, and that I wrote most of the stuff you wrote. Github merge tools were ultra confused so I had to ffffffnaggle it.  Its looking good.  Appreciate all your effort and help adding in the Firbolg race and volo's guide to monsters.

**Comment by cokelito1** [comment]
oki doki, btw did you found what caused the segfault?

**Comment by mattearly** [comment]
I didn't find out what caused it, guessing something was misaligned. Doesn't seem to be happening now.

**Pull request merged**
